# Use new container infrastructure to enable caching
sudo: false

language: c

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64
    | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export STACK="stack --no-terminal --install-ghc"

script: test/script
