name: mai-dz

executables:
  aw:
    main: Main
    source-dirs: aw
  sks:
    main: Main
    source-dirs: sks

dependencies:
  - base
  - hoppy-runtime
  - qtah # qtah-qt5 for the release

ghc-options: -Werror -Wall -Wincomplete-record-updates -Wincomplete-uni-patterns
