resolver: lts-11.10

packages:
  # old
    # - .
    # - aw-qt
  # current:
    - plan-ga

extra-deps:
  # plan-ga:
    - git: https://github.com/afiskon/simple-genetic-algorithm.git
      commit: 5c4542351b8e0ac1b10ff9206277ca7de2484338
    - bookkeeper-0.2.5
    - type-level-sets-0.8.7.0
