resolver: lts-11.2

packages:
  # old
    # - .
    # - aw-qt
  # current:
    - plan-ga

extra-deps:
  # plan-ga:
    - git: https://github.com/cblp/simple-genetic-algorithm.git
      commit: 7eb7289
