name: plan-ga

executable:
  default-extensions:
    - DeriveAnyClass
    - DeriveGeneric
    - FlexibleContexts
    - FlexibleInstances
    - NamedFieldPuns
    - RecordWildCards
    - TupleSections
  ghc-options: -threaded -rtsopts
  main: Main
  other-modules:
    - Data.STRef.Extra

dependencies:
  - base
  - containers
  - deepseq
  - gloss
  - lens
  - mtl
  - random
  - simple-genetic-algorithm

# stack build --trace --exec 'time plan-ga +RTS -p -N'
