name: plan-ga

executable:
  default-extensions:
    - AllowAmbiguousTypes
    - DeriveAnyClass
    - DeriveGeneric
    - FlexibleContexts
    - FlexibleInstances
    - NamedFieldPuns
    - OverloadedLabels
    - Rank2Types
    - RecordWildCards
    - TupleSections
    - TypeFamilies
  ghc-options: -threaded -rtsopts
  main: Main

dependencies:
  - base
  - bookkeeper
  - containers
  - deepseq
  - gloss
  - lens
  - mtl
  - random
  - simple-genetic-algorithm

# stack build --trace --exec 'time plan-ga +RTS -p -N'
